- hosts: localhost
  tasks:
    - name: make capslock another ctrl key
      blockinfile:
        name: /etc/udev/hwdb.d/90-custom-keyboard.hwdb
        create: yes
        block: |
          evdev:atkbd:dmi:*
           KEYBOARD_KEY_3a=leftctrl
      become: true

    - name: rebuild systemd hwdb
      command: systemd-hwdb update
      become: true
